(() => {
 const cms=window.PortfolioCMS, form=document.getElementById('projectForm'), listEl=document.getElementById('projectList'), empty=document.getElementById('emptyEditor');
 let projects=cms.get(), current=null;
 const fields=['id','title','year','category','categoryLabel','accent','cover','video','summary','role','tools','client','challenge','approach'];
 const renderList=()=>{document.getElementById('projectCount').textContent=`${projects.length}`;listEl.innerHTML=projects.map(p=>`<button class="project-item ${current===p.id?'active':''}" data-id="${cms.escape(p.id)}"><span class="project-thumb" style="background-image:url('${cms.escape(p.cover||'')}')"></span><span><strong>${cms.escape(p.title)}</strong><small>${cms.escape(cms.categories[p.category]||p.category)} · ${cms.escape(p.year||'')}</small></span></button>`).join('');listEl.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.id));};
 const open=id=>{const p=projects.find(x=>x.id===id);if(!p)return;current=id;empty.hidden=true;form.hidden=false;fields.forEach(name=>{form.elements[name].value=p[name]||''});form.elements.featured.checked=!!p.featured;form.elements.gallery.value=(p.gallery||[]).join('\n');document.getElementById('editorTitle').textContent=p.title;renderList();};
 const newProject=()=>{const id=`new-project-${Date.now().toString().slice(-5)}`;projects.unshift({id,title:'Untitled Project',year:new Date().getFullYear().toString(),category:'directing',categoryLabel:'Directing',accent:'#b9bec8',cover:'',video:'',summary:'',role:'',tools:'',client:'',challenge:'',approach:'',featured:false,gallery:[]});open(id);};
 form.onsubmit=e=>{e.preventDefault();const old=current;const p={};fields.forEach(name=>p[name]=form.elements[name].value.trim());p.featured=form.elements.featured.checked;p.gallery=form.elements.gallery.value.split('\n').map(x=>x.trim()).filter(Boolean);if(!/^[a-z0-9-]+$/.test(p.id)){alert('Slug can only use lowercase letters, numbers and hyphens.');return;}if(projects.some(x=>x.id===p.id&&x.id!==old)){alert('That slug is already in use.');return;}const index=projects.findIndex(x=>x.id===old);projects[index]=p;current=p.id;cms.save(projects);document.getElementById('editorTitle').textContent=p.title;document.getElementById('saveStatus').textContent='Saved in this browser.';renderList();};
 document.getElementById('newProject').onclick=newProject;
 document.getElementById('deleteProject').onclick=()=>{if(!current||!confirm('Delete this project?'))return;projects=projects.filter(p=>p.id!==current);cms.save(projects);current=null;form.hidden=true;empty.hidden=false;renderList();};
 document.getElementById('previewProject').onclick=()=>{if(current)window.open(`../project/index.html?slug=${encodeURIComponent(current)}`,'_blank');};
 document.getElementById('exportData').onclick=()=>{const blob=new Blob([JSON.stringify(projects,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='shani-portfolio-projects.json';a.click();URL.revokeObjectURL(a.href);};
 document.getElementById('importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data))throw Error();projects=data;cms.save(projects);current=null;form.hidden=true;empty.hidden=false;renderList();}catch{alert('This does not look like a valid project backup.');}};
 document.getElementById('resetData').onclick=()=>{if(!confirm('Restore the original demo projects?'))return;cms.reset();projects=cms.get();current=null;form.hidden=true;empty.hidden=false;renderList();};
 renderList(); if(projects[0]) open(projects[0].id);
})();